# Generated by Django 4.0.5 on 2022-07-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
